### ISSUE TITLE
Crash with latest ImmediatelyFast 1.20.1

### ISSUE THREAD

**Issue by TH3N3WN00B** [fxmorin/memoryLeakFix#143] opened 2023-08-28 00:13 UTC
Crashes with newest version of ImmediatelyFast on 1.20.1

Crash log: https://paste.ee/p/8cwIZ

**Comment by PixusPanic** [comment] 2023-08-28 06:00
Seems to have been an intentional move by ImmediatelyFast, seeing as its changelog and GitHub issues say that it has problems with Sodium:
"Declare MemoryLeakFix <= 1.1.1 as incompatible (This issue has to be fixed by MemoryLeakFix. Uninstall it for now)"

**Comment by TH3N3WN00B** [comment] 2023-08-28 13:47
> Seems to have been an intentional move by ImmediatelyFast, seeing as its changelog and GitHub issues say that it has problems with Sodium: "Declare MemoryLeakFix <= 1.1.1 as incompatible (This issue has to be fixed by MemoryLeakFix. Uninstall it for now)"

Thats why im making this issue on the github, so they are aware of the issue and can fix it, cuz I couldnt find any request mentioning the issue

**Comment by RaphiMC** [comment] 2023-08-28 17:20
This is also a duplicate of #142 and #140 and #139 . I just declared this version of MemoryLeakFix as incompatible so the crash message makes more sense for users

**Comment by FxMorin** [comment] 2023-08-30 18:05
Should be fixed in v1.1.2

**Closed as completed by FxMorin** 2023-08-30 18:05 UTC
