### ISSUE TITLE
MemoryLeakFix related issue

### ISSUE THREAD

**Issue by MCKuma** [fxmorin/memoryLeakFix#132] opened 2023-06-28 20:29 UTC
[crash-2023-06-28_14.16.38-client.txt](https://github.com/fxmorin/MemoryLeakFix/files/11899696/crash-2023-06-28_14.16.38-client.txt)

Crash related to Memory Leak Fix, not consistent so not sure what's causing.

**Comment by FxMorin** [comment] 2023-06-30 03:44
I dont see why MemoryLeakFix would be the cause of a rendering crash.

**Comment by Tursiops-G** [comment] 2023-08-24 20:49
https://github.com/isXander/CullLessLeaves/issues/56#issuecomment-1692382525

**Comment by FxMorin** [comment] 2023-08-30 18:07
Should be fixed in v1.1.2

**Closed as completed by FxMorin** 2023-08-30 18:07 UTC
