### ISSUE TITLE
game crashes with viafabricplus 2.7.3

### ISSUE THREAD

**Issue by ilobilo** [fxmorin/memoryLeakFix#120] opened 2023-05-21 11:39 UTC
https://github.com/FlorianMichael/ViaFabricPlus/issues/103

**Comment by User4716** [comment] 2023-05-27 18:31
I have the same problem

**Comment by User4716** [comment] 2023-05-27 18:39
You can literally reproduce this crash by installing just 2 mods for Fabric 1.19.4 - 0.14.21 
You see below in my CurseForge modpack the mods you need (MemoryLeakFix and ViaFabricPlus)

![screenshot1](https://github.com/fxmorin/MemoryLeakFix/assets/97033682/28ef1c66-c1b5-4732-bd3e-998bbd0427e5)

Here is the full log file: [latest.log](https://github.com/fxmorin/MemoryLeakFix/files/11582781/latest.log)

Below is just the error part:
```
[21:36:37] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/class_310.method_35699(Ljava/io/File;IIII)Lnet/minecraft/class_2561; @310: aload
  Reason:
    Type top (current frame, locals[15]) is not assignable to reference type
  Current Frame:
    bci: @310
    flags: { }
    locals: { 'net/minecraft/class_310', 'java/io/File', integer, integer, integer, integer, 'java/lang/Exception' }
    stack: { 'net/minecraft/class_310', null }
  Bytecode:
    0000000: bb13 6559 01b7 1367 3a0f 1c1d 6806 68b8
    0000010: 136b 2a5f 190f b713 6f3a 06bb 1338 592b
    0000020: 1504 1505 1db7 1372 3a07 1504 861c 866e
    0000030: 3808 1505 861d 866e 3809 1708 1709 959e
    0000040: 0008 1708 a700 0517 0938 0a15 0504 641d
    0000050: 6c1d 6836 0b15 0b9b 0098 0336 0c15 0c15
    0000060: 04a2 0080 03b2 1375 b813 7915 041c 6486
    0000070: 0d6e 0d6a 150c 0568 8666 380d 1505 1d64
    0000080: 860d 6e0d 6a15 0b05 6886 6638 0e17 0d1c
    0000090: 866e 380d 170e 1d86 6e38 0e2a b404 b717
    00000a0: 0a17 0d17 0eb6 137c 1906 b613 8157 110d
    00000b0: 0504 b813 8411 0cf5 04b8 1384 0303 1c1d
    00000c0: 1313 8511 1401 1906 b813 8919 0719 0615
    00000d0: 0c15 0b1c 1db6 138d 150c 1c60 360c a7ff
    00000e0: 7f19 07b6 1390 150b 1d64 360b a7ff 6919
    00000f0: 07b6 1393 3a0b 1906 b813 9719 0bb6 0bb8
    0000100: b813 3fb2 1342 b613 4619 0bba 139c 0000
    0000110: b613 543a 0c13 1356 04bd 0683 5903 190c
    0000120: 53b8 0e32 b03a 06b2 0298 1313 9e19 06b9
    0000130: 13a0 0300 2a01 190f b713 a413 135d 04bd
    0000140: 0683 5903 1906 b613 6053 b80e 32b0     
  Exception Handler Table:
    bci [0, 292] => handler: 293
  Stackmap Table:
    full_frame(@71,{Object[#2],Object[#540],Integer,Integer,Integer,Integer,Object[#4990],Object[#4920],Float,Float,Top,Top,Top,Top,Top,Object[#4965]},{})
    same_locals_1_stack_item_frame(@73,Float)
    full_frame(@85,{Object[#2],Object[#540],Integer,Integer,Integer,Integer,Object[#4990],Object[#4920],Float,Float,Float,Integer,Top,Top,Top,Object[#4965]},{})
    full_frame(@93,{Object[#2],Object[#540],Integer,Integer,Integer,Integer,Object[#4990],Object[#4920],Float,Float,Float,Integer,Integer,Top,Top,Object[#4965]},{})
    same_frame_extended(@225)
    full_frame(@239,{Object[#2],Object[#540],Integer,Integer,Integer,Integer,Object[#4990],Object[#4920],Float,Float,Float,Integer,Top,Top,Top,Object[#4965]},{})
    full_frame(@293,{Object[#2],Object[#540],Integer,Integer,Integer,Integer},{Object[#4860]})

	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
Caused by: java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/class_310.method_35699(Ljava/io/File;IIII)Lnet/minecraft/class_2561; @310: aload
  Reason:
    Type top (current frame, locals[15]) is not assignable to reference type
  Current Frame:
    bci: @310
    flags: { }
    locals: { 'net/minecraft/class_310', 'java/io/File', integer, integer, integer, integer, 'java/lang/Exception' }
    stack: { 'net/minecraft/class_310', null }
  Bytecode:
    0000000: bb13 6559 01b7 1367 3a0f 1c1d 6806 68b8
    0000010: 136b 2a5f 190f b713 6f3a 06bb 1338 592b
    0000020: 1504 1505 1db7 1372 3a07 1504 861c 866e
    0000030: 3808 1505 861d 866e 3809 1708 1709 959e
    0000040: 0008 1708 a700 0517 0938 0a15 0504 641d
    0000050: 6c1d 6836 0b15 0b9b 0098 0336 0c15 0c15
    0000060: 04a2 0080 03b2 1375 b813 7915 041c 6486
    0000070: 0d6e 0d6a 150c 0568 8666 380d 1505 1d64
    0000080: 860d 6e0d 6a15 0b05 6886 6638 0e17 0d1c
    0000090: 866e 380d 170e 1d86 6e38 0e2a b404 b717
    00000a0: 0a17 0d17 0eb6 137c 1906 b613 8157 110d
    00000b0: 0504 b813 8411 0cf5 04b8 1384 0303 1c1d
    00000c0: 1313 8511 1401 1906 b813 8919 0719 0615
    00000d0: 0c15 0b1c 1db6 138d 150c 1c60 360c a7ff
    00000e0: 7f19 07b6 1390 150b 1d64 360b a7ff 6919
    00000f0: 07b6 1393 3a0b 1906 b813 9719 0bb6 0bb8
    0000100: b813 3fb2 1342 b613 4619 0bba 139c 0000
    0000110: b613 543a 0c13 1356 04bd 0683 5903 190c
    0000120: 53b8 0e32 b03a 06b2 0298 1313 9e19 06b9
    0000130: 13a0 0300 2a01 190f b713 a413 135d 04bd
    0000140: 0683 5903 1906 b613 6053 b80e 32b0     
  Exception Handler Table:
    bci [0, 292] => handler: 293
  Stackmap Table:
    full_frame(@71,{Object[#2],Object[#540],Integer,Integer,Integer,Integer,Object[#4990],Object[#4920],Float,Float,Top,Top,Top,Top,Top,Object[#4965]},{})
    same_locals_1_stack_item_frame(@73,Float)
    full_frame(@85,{Object[#2],Object[#540],Integer,Integer,Integer,Integer,Object[#4990],Object[#4920],Float,Float,Float,Integer,Top,Top,Top,Object[#4965]},{})
    full_frame(@93,{Object[#2],Object[#540],Integer,Integer,Integer,Integer,Object[#4990],Object[#4920],Float,Float,Float,Integer,Integer,Top,Top,Object[#4965]},{})
    same_frame_extended(@225)
    full_frame(@239,{Object[#2],Object[#540],Integer,Integer,Integer,Integer,Object[#4990],Object[#4920],Float,Float,Float,Integer,Top,Top,Top,Object[#4965]},{})
    full_frame(@293,{Object[#2],Object[#540],Integer,Integer,Integer,Integer},{Object[#4860]})

	at de.florianmichael.viafabricplus.protocolhack.ProtocolHack.getTargetVersion(ProtocolHack.java:87) ~[viafabricplus-2.7.3.jar:?]
	at net.minecraft.class_1799.handler$zpo000$viafabricplus$allowNegativeItems(class_1799.java:1172) ~[client-intermediary.jar:?]
	at net.minecraft.class_1799.method_7957(class_1799.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_1799.<init>(class_1799.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_1799.<init>(class_1799.java:148) ~[client-intermediary.jar:?]
	at net.minecraft.class_1799.<clinit>(class_1799.java:86) ~[client-intermediary.jar:?]
	at net.minecraft.class_3727.<clinit>(class_3727.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_3726.method_16194(class_3726.java:10) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:903) ~[client-intermediary.jar:?]
	at net.minecraft.class_2248.method_9579(class_2248.java:310) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1153) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:760) ~[client-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1154) ~[client-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:154) ~[fabric-loader-0.14.21-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 2 more

Process crashed with exit code 1
```

**Comment by FxMorin** [comment] 2023-06-08 05:28
~~Will be fixed in next release~~ Nevermind, this most likely needs to be fixed by viaversion

**Comment by florianreuth** [comment] 2023-06-09 19:03
Why do we need to fix this?

**Comment by FxMorin** [comment] 2023-06-10 10:51
Cause you're the ones doing hacky stuff if it breaks this bad

**Comment by x-yingcan-x** [comment] 2023-06-10 13:06
I think this can be closed.
[VFP#103](https://github.com/ViaVersion/ViaFabricPlus/issues/103) for more details

**Comment by florianreuth** [comment] 2023-06-10 13:10
I don't see where I should do "hacky" stuff, after all MemoryLeakFix does load some mixin extension, and since the crash also happens with another mod, I certainly don't assume it's my fault. I can't really find the bug either to be honest, I already went through all my mixins/code: https://github.com/RaphiMC/ImmediatelyFast/issues/67

**Comment by thegatesdev** [comment] 2023-06-12 07:17
> the crash also happens with another mod, [RaphiMC/ImmediatelyFast#67](https://github.com/RaphiMC/ImmediatelyFast/issues/67)

I think this issue is not (yet) related, ImmediatelyFast tries to load a mixin (Minecraft_clientLoadedMixin) that doesn't exist anymore in the current version of MemoryLeakFix, which is why it crashes.
I will try a test build of ImmediatelyFast later today.

**Closed as completed** 2023-06-13 00:25 UTC
Labels: Incompatible
