### ISSUE TITLE
Ticking entities crashing game

### ISSUE THREAD

**Issue by Shoes4Clues** [fxmorin/memoryLeakFix#83] opened 2023-03-15 14:09 UTC
Latest version for 1.18.2 Fabric. Crash logs are attached.
[crash-2023-03-15_06.54.31-server.txt](https://github.com/fxmorin/MemoryLeakFix/files/10980762/crash-2023-03-15_06.54.31-server.txt)

**Comment by Kamiszewskyy** [comment] 2023-03-15 23:47
Can confirm the crash above. I got it multiple times.

**Comment by wendavid552** [comment] 2023-03-19 04:22
It seems to be duplicate of #82 .

**Comment by mulukou** [comment] 2023-03-20 23:15
can confirm, also crashing for me on the latest version, moving it back to 0.7.0 seems to fix the issue

**Comment by FxMorin** [comment] 2023-03-24 18:20
This has been fixed internally and will be in the next release

**Comment by FxMorin** [comment] 2023-03-26 14:21
Duplicate of #82

**Closed as completed by FxMorin** 2023-03-26 14:21 UTC
