### ISSUE TITLE
Labled 1.19.2, but Fabric Loader won't allow it to launch in 1.19.2

### ISSUE THREAD

**Issue by crismantilla** [fxmorin/memoryLeakFix#57] opened 2022-11-23 20:57 UTC
As title says. Here's the error.

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'memory Leak Fix' (memoryleakfix) 1.19-0.7.0 with any version that is compatible with:
		 - minecraft 1.19.2
Unmet dependency listing:
	 - Mod 'memory Leak Fix' (memoryleakfix) 1.19-0.7.0 requires version 1.19 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by SylisMC** [comment] 2022-11-28 01:36
Duplicate of #56 
Use jar memoryleakfix-1.19.1-0.7.0.jar (2nd newest jar)

**Closed as completed** 2022-12-08 20:31 UTC
